{% set org = "mit-crpg" %}
{% set name = "openmc" %}
{% set version = "0.10.0" %}
{% set sha256 = "3940b229f92ca36ae31504a1fca0dbc772c8812203ede9b233916b9ef6ae5f2c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/{{ org }}/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  skip: true  # [win]
  detect_binary_files_with_prefix: true

requirements:
  build:
    - toolchain
    - cmake
    - pkg-config
    - gcc
    - hdf5 1.10.1
    - git
    - setuptools
    - numpy >=1.9
    - cython
    - matplotlib
    - h5py
  run:
    - libgcc
    - libgfortran
    - hdf5 1.10.1
    - python >=2.7
    - six
    - numpy >=1.9
    - h5py
    - scipy
    - pandas
    - matplotlib
    - lxml
    - uncertainties

test:
  commands:
    - test -f "${PREFIX}/bin/openmc"
    - openmc --version

about:
  home: https://openmc.readthedocs.io
  license: MIT
  license_file: LICENSE
  summary: 'OpenMC Monte Carlo Code'
  description: |
    OpenMC is a 3D constructive solid geometry, continuous-energy Monte Carlo
    particle transport code. Particle interaction data is based on HDF5 format
    cross sections, and user input is given in an XML format or controlled
    through the Python API.
  doc_url: https://openmc.readthedocs.io
  dev_url: https://github.com/mit-crpg/openmc

extra:
  recipe-maintainers:
    - scopatz
    - paulromano
